CREATE TABLE "public"."ColumnOptions1"
(
  "varchar1" CHARACTER VARYING (100) DEFAULT '' NOT NULL,
  "text1" CHARACTER VARYING (100) DEFAULT '' NOT NULL,
  "numeric1" NUMERIC (15,4) DEFAULT 0 NOT NULL,
  "numeric2" NUMERIC (15) DEFAULT 0 NOT NULL,
  "numeric3" BIGINT DEFAULT 0 NOT NULL,
  "numeric4" INTEGER DEFAULT 0 NOT NULL,
  "numeric5" SMALLINT DEFAULT 0 NOT NULL,
  "integer1" NUMERIC DEFAULT 0 NOT NULL,
  "integer2" NUMERIC DEFAULT 0 NOT NULL,
  "boolean2" BOOLEAN DEFAULT '0' NOT NULL,
  "bigint1" BIGINT DEFAULT NULL NOT NULL
);
CREATE TABLE "public"."ColumnTypes1"
(
  "string1" TEXT DEFAULT '' NOT NULL,
  "string2" TEXT NOT NULL,
  "string3" TEXT DEFAULT '' NOT NULL,
  "number1" NUMERIC DEFAULT 100 NOT NULL,
  "number2" NUMERIC NOT NULL,
  "number3" NUMERIC DEFAULT 100 NOT NULL,
  "bigint1" BIGINT DEFAULT NULL NOT NULL,
  "bigint2" BIGINT NOT NULL,
  "bigint3" BIGINT DEFAULT NULL NOT NULL,
  "boolean1" BOOLEAN DEFAULT '1' NOT NULL,
  "boolean2" BOOLEAN NOT NULL,
  "boolean3" BOOLEAN DEFAULT '1' NOT NULL, 
  "timestamp1" TIMESTAMP DEFAULT TO_DATE('2021-07-30', 'YYYY-MM-DD') NOT NULL,
  "timestamp2" TIMESTAMP NOT NULL,
  "timestamp3" TIMESTAMP DEFAULT TO_DATE('2021-07-30', 'YYYY-MM-DD') NOT NULL,
  "arraybuffer1" BYTEA DEFAULT NULL NOT NULL,
  "arraybuffer2" BYTEA NOT NULL,
  "arraybuffer3" BYTEA DEFAULT NULL NOT NULL,
  "blob1" BYTEA DEFAULT NULL NOT NULL,
  "blob2" BYTEA NOT NULL,
  "blob3" BYTEA DEFAULT NULL NOT NULL
)